/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author mac
 */
public class ViewPanel extends javax.swing.JPanel {

    private JPanel rightPanel;
    private Car car;
    private CarInformationList carList;
    /**
     * Creates new form ViewPanel
     * @param rightPanel
     * @param car
     * @param carList
     */
    
    public ViewPanel(JPanel rightPanel, Car car, CarInformationList carList) {
        initComponents();
        this.rightPanel = rightPanel;
        this.car = car;
        this.carList = carList;
        txtBrand.setText(car.getBrand());
        txtCity.setText(car.getAvailble_city());
        txtMaxSeats.setText(String.valueOf(car.getMax_seats()));
        txtMinSeats.setText(String.valueOf(car.getMin_seats()));
        txtModelNum.setText(car.getModel_num());
        txtSerialNum.setText(String.valueOf(car.getSerial_num()));
        txtYear.setText(String.valueOf(car.getManufactured_year()));
        chkBoxAvai.setSelected(car.isAvailable());
        chkBoxCert.setSelected(car.isMaintenance_certificate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSerialNum = new javax.swing.JLabel();
        lblModelNum = new javax.swing.JLabel();
        lblMinSeats = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        chkBoxAvai = new javax.swing.JCheckBox();
        chkBoxCert = new javax.swing.JCheckBox();
        txtCity = new javax.swing.JTextField();
        txtSerialNum = new javax.swing.JTextField();
        txtModelNum = new javax.swing.JTextField();
        lblMaxSeats = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblHead = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtBrand = new javax.swing.JTextField();

        lblSerialNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSerialNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNum.setText("Serial Number:");

        lblModelNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblModelNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNum.setText("Model Number:");

        lblMinSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblMinSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSeats.setText("Min Seats:");

        txtMinSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtMinSeats.setEnabled(false);

        chkBoxAvai.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        chkBoxAvai.setText("Available");
        chkBoxAvai.setEnabled(false);
        chkBoxAvai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkBoxAvai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxAvaiActionPerformed(evt);
            }
        });

        chkBoxCert.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        chkBoxCert.setText("Maintenance Certificate");
        chkBoxCert.setEnabled(false);
        chkBoxCert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtCity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCity.setEnabled(false);

        txtSerialNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtSerialNum.setEnabled(false);

        txtModelNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtModelNum.setEnabled(false);

        lblMaxSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblMaxSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxSeats.setText("Max Seats:");

        txtYear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtYear.setEnabled(false);

        txtMaxSeats.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtMaxSeats.setEnabled(false);

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHead.setText("View Car");

        lblBrand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrand.setText("Brand:");

        lblYear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("Manufactured Year:");

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("Available City:");

        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtBrand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtBrand.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(chkBoxAvai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkBoxCert, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMaxSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtYear)
                                    .addComponent(txtMaxSeats)
                                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSerialNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSerialNum)
                                    .addComponent(txtModelNum)
                                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrand)))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHead)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(chkBoxAvai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBoxCert))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNum)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxSeats)
                            .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMinSeats)
                            .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxAvaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxAvaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxAvaiActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        chkBoxAvai.setEnabled(true);
        chkBoxCert.setEnabled(true);
        txtCity.setEnabled(true);
        txtBrand.setEnabled(true);
        txtYear.setEnabled(true);
        txtMaxSeats.setEnabled(true);
        txtMinSeats.setEnabled(true);
        txtModelNum.setEnabled(true);
        txtSerialNum.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp: comps) {
            if (comp instanceof PassengerPanel) {
                PassengerPanel panel = (PassengerPanel) comp;
                panel.populateTable(carList.carList);
                panel.populateCombo();
                panel.updateTime();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtYear.getText());
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a integer number for Manufactured Year!");
            return;
        }

        try {
            Integer.parseInt(txtMaxSeats.getText());
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a integer number for Max Seats!");
            return;
        }

        try {
            Integer.parseInt(txtMinSeats.getText());
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a integer number for Min Seats!");
            return;
        }

        try {
            Integer.parseInt(txtSerialNum.getText());
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a integer number for Serial Number!");
            return;
        }

        car.setAvailable(chkBoxAvai.isSelected());
        car.setAvailble_city(txtCity.getText());
        car.setBrand(txtBrand.getText());
        car.setMaintenance_certificate(chkBoxCert.isSelected());
        car.setManufactured_year(Integer.parseInt(txtYear.getText()));
        car.setMax_seats(Integer.parseInt(txtMaxSeats.getText()));
        car.setMin_seats(Integer.parseInt(txtMinSeats.getText()));
        car.setModel_num(txtModelNum.getText());
        car.setSerial_num(Integer.parseInt(txtSerialNum.getText()));
        JOptionPane.showMessageDialog(null, "Car Updated Successfully");
        Date date = new Date();
        carList.date = date;
        chkBoxAvai.setEnabled(false);
        chkBoxCert.setEnabled(false);
        txtCity.setEnabled(false);
        txtBrand.setEnabled(false);
        txtYear.setEnabled(false);
        txtMaxSeats.setEnabled(false);
        txtMinSeats.setEnabled(false);
        txtModelNum.setEnabled(false);
        txtSerialNum.setEnabled(false);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkBoxAvai;
    private javax.swing.JCheckBox chkBoxCert;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblMaxSeats;
    private javax.swing.JLabel lblMinSeats;
    private javax.swing.JLabel lblModelNum;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSerialNum;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
