/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mac
 */
public class AbnormalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbnormalJPanel
     */
    private VitalSignHistory vsh;
    private double maxBloodPressure;
    private double minBloodPressure;
    public AbnormalJPanel(VitalSignHistory vsh, Double maxBloodPressure, Double minBloodPressure) {
        initComponents();
        this.vsh = vsh;
        this.maxBloodPressure = maxBloodPressure;
        this.minBloodPressure = minBloodPressure;
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)abVitalSignsTable.getModel();
        dtm.setRowCount(0);
        
        for (VitalSigns vs: vsh.getVitalSignHistory()) {
            if (vs.getBloodPressure()>maxBloodPressure || vs.getBloodPressure()<minBloodPressure) {   
                Object row[] = new Object[2];
                row[0] = vs;
                row[1] = vs.getBloodPressure();
                dtm.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloodPresLabel = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        temperatureLabel = new javax.swing.JLabel();
        pulseLabel = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        abnormalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        abVitalSignsTable = new javax.swing.JTable();
        viewDetailBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        tempratureTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        bloodPresTextField = new javax.swing.JTextField();

        bloodPresLabel.setText("Blood Pressure");

        pulseTextField.setEnabled(false);
        pulseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTextFieldActionPerformed(evt);
            }
        });

        temperatureLabel.setText("Temperature");

        pulseLabel.setText("Pulse");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        abnormalLabel.setText("Abnormal Vital Signs");

        abVitalSignsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(abVitalSignsTable);

        viewDetailBtn.setText("View Details");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        tempratureTextField.setEnabled(false);
        tempratureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempratureTextFieldActionPerformed(evt);
            }
        });

        dateTextField.setEnabled(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        dateLabel.setText("Date");

        bloodPresTextField.setEnabled(false);
        bloodPresTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodPresTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abnormalLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pulseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bloodPresLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bloodPresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(temperatureLabel)
                                .addGap(49, 49, 49)
                                .addComponent(tempratureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(abnormalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewDetailBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureLabel)
                    .addComponent(tempratureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPresLabel)
                    .addComponent(bloodPresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulseLabel)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pulseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseTextFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        int selectedrow = abVitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)abVitalSignsTable.getValueAt(selectedrow, 0);
            bloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            tempratureTextField.setText(String.valueOf(vs.getTemperature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());
            abVitalSignsTable.setEnabled(false);
            bloodPresTextField.setEnabled(true);
            tempratureTextField.setEnabled(true);
            pulseTextField.setEnabled(true);
            dateTextField.setEnabled(true);
            saveBtn.setEnabled(true);
            deleteBtn.setEnabled(false);
            viewDetailBtn.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        int selectedrow = abVitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns v = (VitalSigns)abVitalSignsTable.getValueAt(selectedrow, 0);
            double temperature = Double.parseDouble(tempratureTextField.getText());
            double bp = Double.parseDouble(bloodPresTextField.getText());
            int pulse = Integer.parseInt(pulseTextField.getText());
            String date = dateTextField.getText();
            v.setBloodPressure(bp);
            v.setTemperature(temperature);
            v.setPulse(pulse);
            v.setDate(date);
            populateTable();
            JOptionPane.showMessageDialog(null, "Vital Sign Updated Successfully");
            tempratureTextField.setText("");
            bloodPresTextField.setText("");
            pulseTextField.setText("");
            dateTextField.setText("");
            bloodPresTextField.setEnabled(false);
            tempratureTextField.setEnabled(false);
            pulseTextField.setEnabled(false);
            dateTextField.setEnabled(false);
            abVitalSignsTable.setEnabled(true);
            saveBtn.setEnabled(false);
            deleteBtn.setEnabled(true);
            viewDetailBtn.setEnabled(true);
        }else
        JOptionPane.showMessageDialog(null, "Please select any row!");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        // TODO add your handling code here:
        bloodPresTextField.setEnabled(false);
        tempratureTextField.setEnabled(false);
        pulseTextField.setEnabled(false);
        dateTextField.setEnabled(false);
        int selectedrow = abVitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)abVitalSignsTable.getValueAt(selectedrow, 0);
            bloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            tempratureTextField.setText(String.valueOf(vs.getTemperature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
    }//GEN-LAST:event_viewDetailBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        bloodPresTextField.setEnabled(false);
        tempratureTextField.setEnabled(false);
        pulseTextField.setEnabled(false);
        dateTextField.setEnabled(false);
        int selectedrow = abVitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)abVitalSignsTable.getValueAt(selectedrow, 0);
            bloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            tempratureTextField.setText(String.valueOf(vs.getTemperature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());
            int reply = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", null,JOptionPane.YES_NO_OPTION);
            if(reply == 0) {
                vsh.deleteVitals(vs);
                bloodPresTextField.setText("");
                tempratureTextField.setText("");
                pulseTextField.setText("");
                dateTextField.setText("");
            }else
            return;
            populateTable();
            JOptionPane.showMessageDialog(null, "Vital sign has been deleted!");

        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tempratureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempratureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempratureTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void bloodPresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodPresTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPresTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable abVitalSignsTable;
    private javax.swing.JLabel abnormalLabel;
    private javax.swing.JLabel bloodPresLabel;
    private javax.swing.JTextField bloodPresTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JTextField tempratureTextField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
