/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mac
 */
public class ViewVitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalsJPanel
     */
    private VitalSignHistory vsh;
    public ViewVitalsJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)VitalSignsTable.getModel();
        dtm.setRowCount(0);
        
        for (VitalSigns vs: vsh.getVitalSignHistory()) {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);
            
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignsTable = new javax.swing.JTable();
        ViewDetailBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        TempratureTextField = new javax.swing.JTextField();
        DateTextField = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        BloodPresTextField = new javax.swing.JTextField();
        BloodPresLabel = new javax.swing.JLabel();
        PulseTextField = new javax.swing.JTextField();
        TemperatureLabel = new javax.swing.JLabel();
        PulseLabel = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        ViewLabel.setText("View Vital Signs");

        VitalSignsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VitalSignsTable);

        ViewDetailBtn.setText("View Detail");
        ViewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        TempratureTextField.setEnabled(false);
        TempratureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempratureTextFieldActionPerformed(evt);
            }
        });

        DateTextField.setEnabled(false);
        DateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextFieldActionPerformed(evt);
            }
        });

        DateLabel.setText("Date");

        BloodPresTextField.setEnabled(false);
        BloodPresTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPresTextFieldActionPerformed(evt);
            }
        });

        BloodPresLabel.setText("Blood Pressure");

        PulseTextField.setEnabled(false);
        PulseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulseTextFieldActionPerformed(evt);
            }
        });

        TemperatureLabel.setText("Temperature");

        PulseLabel.setText("Pulse");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(PulseLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BloodPresLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BloodPresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(TemperatureLabel)
                            .addGap(49, 49, 49)
                            .addComponent(TempratureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(ViewLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewDetailBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperatureLabel)
                    .addComponent(TempratureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodPresLabel)
                    .addComponent(BloodPresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PulseLabel)
                    .addComponent(PulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailBtnActionPerformed
        // TODO add your handling code here:
        BloodPresTextField.setEnabled(false);
        TempratureTextField.setEnabled(false);
        PulseTextField.setEnabled(false);
        DateTextField.setEnabled(false);
        int selectedrow = VitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)VitalSignsTable.getValueAt(selectedrow, 0);
            BloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            TempratureTextField.setText(String.valueOf(vs.getTemperature()));
            PulseTextField.setText(String.valueOf(vs.getPulse()));
            DateTextField.setText(vs.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
    }//GEN-LAST:event_ViewDetailBtnActionPerformed

    private void TempratureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempratureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempratureTextFieldActionPerformed

    private void DateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTextFieldActionPerformed

    private void BloodPresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPresTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPresTextFieldActionPerformed

    private void PulseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PulseTextFieldActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        BloodPresTextField.setEnabled(false);
        TempratureTextField.setEnabled(false);
        PulseTextField.setEnabled(false);
        DateTextField.setEnabled(false);
        int selectedrow = VitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)VitalSignsTable.getValueAt(selectedrow, 0);
            BloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            TempratureTextField.setText(String.valueOf(vs.getTemperature()));
            PulseTextField.setText(String.valueOf(vs.getPulse()));
            DateTextField.setText(vs.getDate());
            int reply = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", null,JOptionPane.YES_NO_OPTION);
            if(reply == 0) {
                vsh.deleteVitals(vs);
                BloodPresTextField.setText("");
                TempratureTextField.setText("");
                PulseTextField.setText("");
                DateTextField.setText("");
            }else 
                return;
            populateTable();
            JOptionPane.showMessageDialog(null, "Vital sign has been deleted!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = VitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns vs = (VitalSigns)VitalSignsTable.getValueAt(selectedrow, 0);
            BloodPresTextField.setText(String.valueOf(vs.getBloodPressure()));
            TempratureTextField.setText(String.valueOf(vs.getTemperature()));
            PulseTextField.setText(String.valueOf(vs.getPulse()));
            DateTextField.setText(vs.getDate());
            VitalSignsTable.setEnabled(false);
            BloodPresTextField.setEnabled(true);
            TempratureTextField.setEnabled(true);
            PulseTextField.setEnabled(true);
            DateTextField.setEnabled(true);
            saveBtn.setEnabled(true);
            DeleteBtn.setEnabled(false);
            ViewDetailBtn.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
        
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = VitalSignsTable.getSelectedRow();
        if(selectedrow >= 0) {
            VitalSigns v = (VitalSigns)VitalSignsTable.getValueAt(selectedrow, 0);
            double temperature = Double.parseDouble(TempratureTextField.getText());
            double bp = Double.parseDouble(BloodPresTextField.getText());
            int pulse = Integer.parseInt(PulseTextField.getText());
            String date = DateTextField.getText();
            v.setBloodPressure(bp);
            v.setTemperature(temperature);
            v.setPulse(pulse);
            v.setDate(date);
            JOptionPane.showMessageDialog(null, "Vital Sign Updated Successfully");
            populateTable();
            TempratureTextField.setText("");
            BloodPresTextField.setText("");
            PulseTextField.setText("");
            DateTextField.setText("");
            BloodPresTextField.setEnabled(false);
            TempratureTextField.setEnabled(false);
            PulseTextField.setEnabled(false);
            DateTextField.setEnabled(false);
            VitalSignsTable.setEnabled(true);
            saveBtn.setEnabled(false);
            DeleteBtn.setEnabled(true);
            ViewDetailBtn.setEnabled(true);
        }else 
            JOptionPane.showMessageDialog(null, "Please select any row!");
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPresLabel;
    private javax.swing.JTextField BloodPresTextField;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel PulseLabel;
    private javax.swing.JTextField PulseTextField;
    private javax.swing.JLabel TemperatureLabel;
    private javax.swing.JTextField TempratureTextField;
    private javax.swing.JButton ViewDetailBtn;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JTable VitalSignsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
