/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryGuyRole;

import Interface.ChefRole.*;
import Business.Enterprise.Enterprise;
import Business.Organization.ChefOrganization;
import Business.Organization.DeliveryGuyOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CookWorkRequest;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class DeliveryGuyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryGuyWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private DeliveryGuyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    public DeliveryGuyWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = (DeliveryGuyOrganization)organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)orderRequestTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = ((DeliveryWorkRequest)request).getOrderWorkRequest().getOrderId();
            row[1] = (DeliveryWorkRequest)request;
            row[2] = ((DeliveryWorkRequest)request).getOrderWorkRequest().getSender().getAddress();
            row[3] = ((DeliveryWorkRequest)request).getOrderWorkRequest().getRestaurant().getAddress();
//            row[3] = ((DeliveryWorkRequest)request).getOrderWorkRequest().getFoodDirectory().getFoodList().size();
            row[4] = ((DeliveryWorkRequest)request).getOrderWorkRequest().getStatus();
            
            model.addRow(row);
        }
        if(!userAccount.getWorkQueue().getWorkRequestList().isEmpty()) {
            btnAccept.setEnabled(false);
            btnFinish.setEnabled(true);
            txtOrderID.setText(String.valueOf(((DeliveryWorkRequest)userAccount.getWorkQueue()
                    .getWorkRequestList().get(0)).getOrderWorkRequest().getOrderId()));
        }
        else{
            btnAccept.setEnabled(true);
            btnFinish.setEnabled(false);
            txtOrderID.setText("No Order Delivering");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderRequestTable = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        btnFinish = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 246, 246));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Delivery Guy Work Area");

        orderRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Time", "Customer Address", "Restaurant Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderRequestTable);

        btnAccept.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAccept.setText("Accept Delivery");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        jLabel1.setText("You are delivering Order:");

        txtOrderID.setEnabled(false);

        btnFinish.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnFinish.setText("Finish Delivery");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(337, 337, 337))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        if(orderRequestTable.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(null, "Please select a request first!");
            return;
        }
        
        DeliveryWorkRequest r = (DeliveryWorkRequest)orderRequestTable.getValueAt(orderRequestTable.getSelectedRow(), 1);
        
        String status = r.getOrderWorkRequest().getStatus();
        
        if(!status.equals("Waiting For Pick"))
        {
            JOptionPane.showMessageDialog(null, "This order has been accepted by other delivery guys!");
            return;
        }
        userAccount.getWorkQueue().getWorkRequestList().add(r);
        r.getOrderWorkRequest().setStatus("Delivering");
        populateTable();
        JOptionPane.showMessageDialog(null, "Accept Order "+r.getOrderWorkRequest().getOrderId());
        //
       
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        DeliveryWorkRequest dwr = (DeliveryWorkRequest)userAccount.getWorkQueue().getWorkRequestList().get(0);
        dwr.getOrderWorkRequest().setStatus("Delivered");
        dwr.getOrderWorkRequest().setResolveDate();
        userAccount.getWorkQueue().getWorkRequestList().remove(dwr);
        populateTable();
    }//GEN-LAST:event_btnFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderRequestTable;
    private javax.swing.JTextField txtOrderID;
    // End of variables declaration//GEN-END:variables
}
