/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SysAdminRole;

import Business.Network.Network;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.DeliveryServiceEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Enterprise.RestaurantEnterprise;
import Business.Role.DeliveryAdminRole;
import Business.Role.RestAdminRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageEnterpriseManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    private JPanel rightpanel;
    private EcoSystem ecoSystem;
    
    public ManageEnterpriseManagerJPanel(JPanel rightpanel, EcoSystem ecoSystem) {
        initComponents();
        this.rightpanel = rightpanel;
        this.ecoSystem = ecoSystem;
        
        populate();
        popOrganizationComboBox();
    }
    
    public void populate()
    {
        int rowCount = enterprisemanagerTbl.getRowCount();
        jScrollPane1.getViewport().setBackground(new Color(249,246,246));
        DefaultTableModel dtm = (DefaultTableModel) enterprisemanagerTbl.getModel();
        for(int i = rowCount - 1; i >= 0; i--)
        {
            dtm.removeRow(i);
        }
        
        for(Network network : ecoSystem.getNetworkList())
        {                  
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
            {
                for (UserAccount account : enterprise.getUserAccountDirectory().getUserAccountList())
                {
                    Object row[] = new Object[dtm.getColumnCount()];
                    row[0] = network;
                    row[1] = enterprise.getEnterpriseType();
                    row[2] = enterprise.getName();
                    row[3] = account.getUsername();
                    row[4] = account.getPassword();
                    dtm.addRow(row);
                }
            }
        }
    }
    
    public void popOrganizationComboBox()
    {
        LocationComboBox.removeAllItems();
        for (Network network : ecoSystem.getNetworkList())
        {
            LocationComboBox.addItem(network);
        }
        TypeComboBox.removeAllItems();
        TypeComboBox.addItem(Enterprise.EnterpriseType.DeliveryService);
        TypeComboBox.addItem(Enterprise.EnterpriseType.Restaurant);
        LocationComboBox.setSelectedIndex(-1);
        TypeComboBox.setSelectedIndex(-1);
    }
    
    private void populateEnterpriseComboBox(Network network, EnterpriseType type)
    {
        EnterpriseNameComboBox.removeAllItems();
        if(type == Enterprise.EnterpriseType.DeliveryService) {
            for (Enterprise dse: network.getEnterpriseDirectory().getDeliveryServiceList())
                EnterpriseNameComboBox.addItem(dse);
        }
        else {
            for (Enterprise re: network.getEnterpriseDirectory().getRestaurantList())
                EnterpriseNameComboBox.addItem(re);
        }
           
        EnterpriseNameComboBox.setSelectedIndex(-1);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisemanagerTbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        RegisterBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LocationComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employeeTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        EnterpriseNameComboBox = new javax.swing.JComboBox();
        PasswordTxt = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(881, 614));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        enterprisemanagerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NetWork", "Enterprise Type", "Enterprise Name", "Manager Name", "Manager Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterprisemanagerTbl);
        if (enterprisemanagerTbl.getColumnModel().getColumnCount() > 0) {
            enterprisemanagerTbl.getColumnModel().getColumn(0).setResizable(false);
            enterprisemanagerTbl.getColumnModel().getColumn(1).setResizable(false);
            enterprisemanagerTbl.getColumnModel().getColumn(2).setResizable(false);
            enterprisemanagerTbl.getColumnModel().getColumn(3).setResizable(false);
            enterprisemanagerTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 250));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel2.setText("UserName:");

        NameTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });

        RegisterBtn.setBackground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RegisterBtn.setText("Create");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel6.setText("Location：");

        LocationComboBox.setBackground(new java.awt.Color(255, 255, 255));
        LocationComboBox.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        LocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 36)); // NOI18N
        jLabel4.setText("Create Enterprise Manager");

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel10.setText("Employee Name:");

        employeeTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel11.setText("Enterprise Type：");

        TypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        TypeComboBox.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel12.setText("Enterprise Name：");

        EnterpriseNameComboBox.setBackground(new java.awt.Color(255, 255, 255));
        EnterpriseNameComboBox.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        EnterpriseNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterpriseNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(EnterpriseNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(PasswordTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeTxt)
                            .addComponent(RegisterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                .addGap(211, 211, 211))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BackBtn)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(EnterpriseNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addComponent(RegisterBtn)
                .addGap(49, 49, 49))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 860, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) EnterpriseNameComboBox.getSelectedItem();
        String username = NameTxt.getText();
        String password = String.valueOf(PasswordTxt.getPassword());
        String employeename = employeeTxt.getText();
        if(enterprise == null){
            JOptionPane.showMessageDialog(null, "Please select a enterprise!");
            return; 
        }
        if(username.isEmpty() || password.isEmpty() || employeename.isEmpty()){
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
            return;
        }
        if(!ecoSystem.checkIfUserIsUnique(username)){
            JOptionPane.showMessageDialog(null, "Username has existed!");
            return;
        }
        
        
        
        Employee employee = enterprise.getEmployeeDirectory().createEmployee(employeename);
        Role role;
        if (enterprise.getEnterpriseType() == EnterpriseType.Restaurant)
            role = new RestAdminRole();
        else
            role = new DeliveryAdminRole();
        UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, role);
        populate();    
        NameTxt.setText("");
        PasswordTxt.setText("");
        employeeTxt.setText("");
        EnterpriseNameComboBox.setSelectedIndex(-1);
        TypeComboBox.setSelectedIndex(-1);
        LocationComboBox.setSelectedIndex(-1);
        
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.rightpanel.remove(this);
        Component[] componentArray = rightpanel.getComponents();
        //refresh table
        for(Component comp : componentArray){
            if(comp instanceof SysAdminWorkAreaJPanel){
                SysAdminWorkAreaJPanel manageP = (SysAdminWorkAreaJPanel) comp;
                manageP.populateTree();
            }
        }
        CardLayout cardlayout =  (CardLayout)this.rightpanel.getLayout();
        cardlayout.previous(rightpanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) LocationComboBox.getSelectedItem();
        EnterpriseType type = (EnterpriseType)TypeComboBox.getSelectedItem();
        if(network != null && type != null) 
        {
            populateEnterpriseComboBox(network, type);
        }
        else
        {
            this.EnterpriseNameComboBox.removeAllItems();
        }
    }//GEN-LAST:event_TypeComboBoxActionPerformed

    private void LocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) LocationComboBox.getSelectedItem();
        EnterpriseType type = (EnterpriseType)TypeComboBox.getSelectedItem();
        if (network != null && type != null)
        {
            populateEnterpriseComboBox(network,type);
        }
        
        else
        {
            this.EnterpriseNameComboBox.removeAllItems();
        }
    }//GEN-LAST:event_LocationComboBoxActionPerformed

    private void EnterpriseNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterpriseNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterpriseNameComboBoxActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox EnterpriseNameComboBox;
    private javax.swing.JComboBox LocationComboBox;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JComboBox TypeComboBox;
    private javax.swing.JTextField employeeTxt;
    private javax.swing.JTable enterprisemanagerTbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
