/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.TravelAgency;
import UserInterface.ManageFlights.ManageFlightsJPanel;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import UserInterface.Office.TravelOfficeLogInJPanel;
import java.awt.CardLayout;

/**
 *
 * @author mac
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    private TravelAgency TA;
    public TravelAgencyMain() {
        initComponents();
        TA = new TravelAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AbsoluteJPanel = new javax.swing.JPanel();
        taBtn = new javax.swing.JButton();
        airlinerBtn = new javax.swing.JButton();
        toBtn = new javax.swing.JButton();
        CardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbsoluteJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taBtn.setText("Travel Agency");
        taBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBtnActionPerformed(evt);
            }
        });
        AbsoluteJPanel.add(taBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 40));

        airlinerBtn.setText("Airliner");
        airlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerBtnActionPerformed(evt);
            }
        });
        AbsoluteJPanel.add(airlinerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 40));

        toBtn.setText("Travel Office");
        toBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBtnActionPerformed(evt);
            }
        });
        AbsoluteJPanel.add(toBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 120, 40));

        jSplitPane1.setLeftComponent(AbsoluteJPanel);

        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        ManageAirlinersJPanel ma = new ManageAirlinersJPanel(CardSequenceJPanel, TA);
        CardSequenceJPanel.add("ManageAirliners", ma);
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_taBtnActionPerformed

    private void airlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        ManageFlightsJPanel mf = new ManageFlightsJPanel(CardSequenceJPanel, TA);
        CardSequenceJPanel.add("ManageFlights", mf);
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_airlinerBtnActionPerformed

    private void toBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        TravelOfficeLogInJPanel toli = new TravelOfficeLogInJPanel(CardSequenceJPanel, TA);
        CardSequenceJPanel.add("TravelOfficeLogIn", toli);
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_toBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbsoluteJPanel;
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton airlinerBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton taBtn;
    private javax.swing.JButton toBtn;
    // End of variables declaration//GEN-END:variables
}
