/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.Food.Food;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class OrderDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetailsJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    OrderWorkRequest order;
    
    OrderDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, OrderWorkRequest order) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.order = order;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populate() {
        DefaultTableModel dtm = (DefaultTableModel)tblOrdered.getModel();
        dtm.setRowCount(0);
        float total = 0;
        for(Food food: order.getFoodDirectory().getFoodList()) {
            Object[] row = new Object[dtm.getColumnCount()];
             row[0] = food;
             row[1] = food.getPrice();
             total += food.getPrice();
             dtm.addRow(row);
        }
        txtTotal.setText(String.valueOf(total));
        txtRestaurant.setText(order.getRestaurant().getName());
        txtStatus.setText(order.getStatus());
        txtOrderTime.setText(order.getRequestDate());
        if (order.getStatus().equals("Delivered")) {
            btnAcknowledge.setEnabled(true);
            txtDeliveryTime.setText(order.getResolveDate());
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdered = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnEvaFood = new javax.swing.JButton();
        btnEvaDS = new javax.swing.JButton();
        btnAcknowledge = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRestaurant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrderTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDeliveryTime = new javax.swing.JTextField();
        btnF1 = new javax.swing.JRadioButton();
        btnF2 = new javax.swing.JRadioButton();
        btnF4 = new javax.swing.JRadioButton();
        btnF3 = new javax.swing.JRadioButton();
        btnF5 = new javax.swing.JRadioButton();
        btnDS1 = new javax.swing.JRadioButton();
        btnDS5 = new javax.swing.JRadioButton();
        btnDS4 = new javax.swing.JRadioButton();
        btnDS3 = new javax.swing.JRadioButton();
        btnDS2 = new javax.swing.JRadioButton();
        BackBtn = new javax.swing.JButton();

        buttonGroup1.add(btnF1);
        buttonGroup1.add(btnF2);
        buttonGroup1.add(btnF3);
        buttonGroup1.add(btnF4);
        buttonGroup1.add(btnF5);

        buttonGroup2.add(btnDS1);
        buttonGroup2.add(btnDS2);
        buttonGroup2.add(btnDS3);
        buttonGroup2.add(btnDS4);
        buttonGroup2.add(btnDS5);

        tblOrdered.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrdered);

        jLabel1.setText("Total:");

        txtTotal.setEnabled(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnEvaFood.setText("Evaluate Food");
        btnEvaFood.setEnabled(false);
        btnEvaFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaFoodActionPerformed(evt);
            }
        });

        btnEvaDS.setText("Evaluate Delivery Service");
        btnEvaDS.setEnabled(false);
        btnEvaDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaDSActionPerformed(evt);
            }
        });

        btnAcknowledge.setText("Receipt Acknowledge");
        btnAcknowledge.setEnabled(false);
        btnAcknowledge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcknowledgeActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Status:");

        txtStatus.setEnabled(false);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Restaurant:");

        txtRestaurant.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Order Time:");

        txtOrderTime.setEnabled(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Delivery Time:");

        txtDeliveryTime.setEnabled(false);

        btnF1.setText("1");

        btnF2.setText("2");

        btnF4.setText("4");

        btnF3.setText("3");

        btnF5.setText("5");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        btnDS1.setText("1");

        btnDS5.setText("5");
        btnDS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDS5ActionPerformed(evt);
            }
        });

        btnDS4.setText("4");

        btnDS3.setText("3");

        btnDS2.setText("2");

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEvaFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEvaDS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDS1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDS2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDS3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDS4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDS5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnF1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnF5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrderTime)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDeliveryTime)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAcknowledge))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBtn)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrderTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAcknowledge)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(93, 93, 93)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEvaFood)
                    .addComponent(btnF1)
                    .addComponent(btnF2)
                    .addComponent(btnF4)
                    .addComponent(btnF3)
                    .addComponent(btnF5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEvaDS)
                    .addComponent(btnDS1)
                    .addComponent(btnDS2)
                    .addComponent(btnDS4)
                    .addComponent(btnDS3)
                    .addComponent(btnDS5))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnEvaDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaDSActionPerformed
        // TODO add your handling code here:
        int evaluation = 0;
        if(btnDS1.isSelected()) evaluation = 1;
        else if(btnDS2.isSelected()) evaluation = 2;
        else if(btnDS3.isSelected()) evaluation = 3;
        else if(btnDS4.isSelected()) evaluation = 4;
        else if(btnDS5.isSelected()) evaluation = 5;
        else {
            JOptionPane.showMessageDialog(null, "Please select a point for the food");
            return;
        }
        order.getDeliveryService().setEvaluation(evaluation);
        JOptionPane.showMessageDialog(null, "Thank you for your evaluation!");
        btnEvaDS.setEnabled(false);
    }//GEN-LAST:event_btnEvaDSActionPerformed

    private void btnAcknowledgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcknowledgeActionPerformed
        // TODO add your handling code here:
        btnEvaFood.setEnabled(true);
        btnEvaDS.setEnabled(true);
        order.setStatus("Customer Acknowledged");
        txtStatus.setText(order.getStatus());
        btnAcknowledge.setEnabled(false);
    }//GEN-LAST:event_btnAcknowledgeActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void btnEvaFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaFoodActionPerformed
        // TODO add your handling code here:
        int evaluation = 0;
        if(btnF1.isSelected()) evaluation = 1;
        else if(btnF2.isSelected()) evaluation = 2;
        else if(btnF3.isSelected()) evaluation = 3;
        else if(btnF4.isSelected()) evaluation = 4;
        else if(btnF5.isSelected()) evaluation = 5;
        else {
            JOptionPane.showMessageDialog(null, "Please select a point for the food");
            return;
        }
        order.getRestaurant().setEvaluation(evaluation);
        for (Food food: order.getFoodDirectory().getFoodList()) {
            food.setEvaluate(evaluation);
        }
        JOptionPane.showMessageDialog(null, "Thank you for your evaluation!");
        btnEvaFood.setEnabled(false);
    }//GEN-LAST:event_btnEvaFoodActionPerformed

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF5ActionPerformed

    private void btnDS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDS5ActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        //refresh table
        for(Component comp : componentArray){
            if(comp instanceof CustomerWorkAreaJPanel){
                CustomerWorkAreaJPanel manageP = (CustomerWorkAreaJPanel) comp;
                manageP.populate();
            }
        }
        CardLayout cardlayout = (CardLayout)this.userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton btnAcknowledge;
    private javax.swing.JRadioButton btnDS1;
    private javax.swing.JRadioButton btnDS2;
    private javax.swing.JRadioButton btnDS3;
    private javax.swing.JRadioButton btnDS4;
    private javax.swing.JRadioButton btnDS5;
    private javax.swing.JButton btnEvaDS;
    private javax.swing.JButton btnEvaFood;
    private javax.swing.JRadioButton btnF1;
    private javax.swing.JRadioButton btnF2;
    private javax.swing.JRadioButton btnF3;
    private javax.swing.JRadioButton btnF4;
    private javax.swing.JRadioButton btnF5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrdered;
    private javax.swing.JTextField txtDeliveryTime;
    private javax.swing.JTextField txtOrderTime;
    private javax.swing.JTextField txtRestaurant;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
