/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryAdminRole;

import Business.Enterprise.DeliveryServiceEnterprise;
import Interface.RestAdminRole.*;
import Business.Enterprise.RestaurantEnterprise;
import Business.Food.Food;
import Business.Network.Network;
import Business.Organization.DeliveryGuyOrganization;
import Business.Organization.Organization;
import Business.Role.ChefRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CookWorkRequest;
import Business.WorkQueue.DeliveryWorkRequest;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wangbaichao
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    
    private DeliveryServiceEnterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public ManageOrderJPanel(JPanel userProcessContainer,UserAccount userAccount,DeliveryServiceEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount=userAccount;
        
        populateTable();
        popdeliComboBox();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)deliveryRequestTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = (OrderWorkRequest)request;
            row[1] = ((OrderWorkRequest)request).getSender().getAddress();
            row[2] = ((OrderWorkRequest)request).getFoodDirectory().getFoodList().size();
            row[3] = ((OrderWorkRequest)request).getRestaurant().getAddress();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    public void popdeliComboBox()
    {
        deliComboBox.removeAllItems();
        
        
        for (Organization o: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o.getSupportedRole().get(0).getRoleType()==Role.RoleType.DeliveryGuy){
               
                deliComboBox.addItem(o);
            }
            
        }
        deliComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryRequestTable = new javax.swing.JTable();
        btnDetials = new javax.swing.JButton();
        btnSent = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        deliComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(249, 246, 246));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Manage Order");

        deliveryRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Customer Address", "Food Number", "Restaurant Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deliveryRequestTable);

        btnDetials.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnDetials.setText("View Detials");
        btnDetials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetialsActionPerformed(evt);
            }
        });

        btnSent.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSent.setText("Send to Organization");
        btnSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        deliComboBox.setBackground(new java.awt.Color(255, 255, 255));
        deliComboBox.setFont(new java.awt.Font("Mshtakan", 1, 14)); // NOI18N
        deliComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery" }));
        deliComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(696, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetials, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSent, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetials, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deliComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnDetialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetialsActionPerformed
        // TODO add your handling code here:
        int selectedRow = deliveryRequestTable.getSelectedRow();

        if(selectedRow>=0){
            OrderWorkRequest a = (OrderWorkRequest)deliveryRequestTable.getValueAt(selectedRow, 0);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add("UpdateAirplaneJPanel", 
                new requestDetialJPanel(userProcessContainer,enterprise, a));
            layout.next(userProcessContainer);

        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnDetialsActionPerformed

    private void btnSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentActionPerformed
        // TODO add your handling code here:
        if(deliveryRequestTable.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(null, "Please select a request first!");
            return;
        }
        if(deliComboBox.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Please select a delivery organization!");
            return;
        }
        OrderWorkRequest r = (OrderWorkRequest)deliveryRequestTable.getValueAt(deliveryRequestTable.getSelectedRow(), 0);
        
        String status = r.getStatus();
        
        if(status.equals("Waiting For Delivery")){
            DeliveryWorkRequest deliveryOrder = new DeliveryWorkRequest(r);
            DeliveryGuyOrganization deliveryOrg = (DeliveryGuyOrganization)deliComboBox.getSelectedItem();
            deliveryOrg.getWorkQueue().getWorkRequestList().add(deliveryOrder);
            deliveryOrder.getOrderWorkRequest().setStatus("Waiting For Pick");
            deliveryOrder.setSender(userAccount);
            populateTable();
            JOptionPane.showMessageDialog(null, "Request successfully sent!");
            return;
        }
        else if(!status.equals("Waiting For Delivery")){
            JOptionPane.showMessageDialog(null, "Request can't be sent!");
            return;
        }
        
           
       
        
    }//GEN-LAST:event_btnSentActionPerformed

    private void deliComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnDetials;
    private javax.swing.JButton btnSent;
    private javax.swing.JComboBox<Object> deliComboBox;
    private javax.swing.JTable deliveryRequestTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
