/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Office;

import Business.Airliner.Flight;
import Business.Airliner.Seat;
import Business.Customer;
import Business.Ticket;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class ChooseSeatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChooseSeatJPanel
     */
    private JPanel CardSequenceJPanel;
    private Customer customer;
    private Flight flight;
    

    ChooseSeatJPanel(JPanel CardSequenceJPanel, Customer customer, Flight flight) {
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.customer = customer;
        this.flight = flight;
        initComponents();
        initiate();
    }

    private void initiate() {
         
        ListSelectionModel dtm = (ListSelectionModel)tblSeats.getSelectionModel();
        tblSeats.setCellSelectionEnabled(true);
        for (int i = 0; i < 25; i++) {
            for (int j = 0; j < 6; j++) {
                tblSeats.setValueAt(flight.getSeats()[i][j], i, j);
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();

        tblSeats.setBackground(new java.awt.Color(204, 204, 255));
        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Window", "Middle", "Aisle", "Aisle", "Middle", "Window"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSeats);
        if (tblSeats.getColumnModel().getColumnCount() > 0) {
            tblSeats.getColumnModel().getColumn(0).setResizable(false);
            tblSeats.getColumnModel().getColumn(1).setResizable(false);
            tblSeats.getColumnModel().getColumn(2).setResizable(false);
            tblSeats.getColumnModel().getColumn(3).setResizable(false);
            tblSeats.getColumnModel().getColumn(4).setResizable(false);
            tblSeats.getColumnModel().getColumn(5).setResizable(false);
        }

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnBook)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        Component[] comps = this.CardSequenceJPanel.getComponents();
        for (Component comp: comps) {
            if (comp instanceof BookTicketJPanel) {
                BookTicketJPanel panel = (BookTicketJPanel) comp;
                panel.populate();
            }
        }
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblSeats.getSelectedRow();
        int selectedcol = tblSeats.getSelectedColumn();
        if(selectedrow >= 0 && selectedcol >= 0) {
            Seat seat = (Seat)tblSeats.getValueAt(selectedrow, selectedcol);
            if (!seat.isAvailable()) {
                JOptionPane.showMessageDialog(null, "This seat has been booked!");
                return;
            }    
            int reply = JOptionPane.showConfirmDialog(null, 
                    "Are you sure to book this seat with $"+seat.getPrice() +"?", 
                    null,JOptionPane.YES_NO_OPTION);
            if(reply == 0) {
                Ticket ticket = new Ticket(customer, seat);
                customer.setTicket(ticket);
            }else
                return;
            
            JOptionPane.showMessageDialog(null, "You have booked this seat successfully!");
            seat.setAvailable(false);
            flight.setAvaiSeat(flight.getAvaiSeat() - 1);
            initiate();
        } 
        else {
            JOptionPane.showMessageDialog(null, "Please select any unit!");
        }
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeats;
    // End of variables declaration//GEN-END:variables
}
