/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Office;

import Business.TravelAgency;
import Business.TravelOffice;
import UserInterface.ManageFlights.EditFlightJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mac
 */
public class TravelOfficeRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelOfficeLoginJPanel
     */
    private JPanel CardSequenceJPanel;
    private TravelAgency TA;

    TravelOfficeRegisterJPanel(JPanel CardSequenceJPanel, TravelAgency TA) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.TA = TA;
        passwordListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        txtRePwd = new javax.swing.JPasswordField();
        txtLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("re-enter password :");

        btnRegister.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Office Name:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("password:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register Your Travel Office ");

        txtPwd.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        txtRePwd.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePwdActionPerformed(evt);
            }
        });

        txtLocation.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Location:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLocation)
                        .addComponent(txtPwd)
                        .addComponent(txtRePwd)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordListener() {
        txtPwd.getDocument().addDocumentListener(new DocumentListener(){
            
            Border border = new JTextField().getBorder();
            @Override
            public void changedUpdate(DocumentEvent e) {}
            
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (String.valueOf(txtPwd.getPassword()).equals("") || passwordPattern()){
                    txtPwd.setBorder(border);
                    jLabel2.setForeground(Color.BLACK);
                }
                else {
                    txtPwd.setBorder(BorderFactory.createLineBorder(Color.red));
                    jLabel2.setForeground(Color.red);
                }
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                if (String.valueOf(txtPwd.getPassword()).equals("") || passwordPattern()){
                    txtPwd.setBorder(border);
                    jLabel2.setForeground(Color.BLACK);
                }
                else {
                    txtPwd.setBorder(BorderFactory.createLineBorder(Color.red));
                    jLabel2.setForeground(Color.red);
                }
            }

        });
        
        txtRePwd.getDocument().addDocumentListener(new DocumentListener(){
            
            Border border = new JTextField().getBorder();
            
            @Override
            public void changedUpdate(DocumentEvent e) {}
            
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (!String.valueOf(txtRePwd.getPassword()).
                        equals(String.valueOf(txtPwd.getPassword()))){
                    txtRePwd.setBorder(BorderFactory.createLineBorder(Color.red));
                    jLabel3.setForeground(Color.red);
                }
                else {
                    txtRePwd.setBorder(border);
                    jLabel3.setForeground(Color.BLACK);
                }
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                if (!String.valueOf(txtRePwd.getPassword()).
                        equals(String.valueOf(txtPwd.getPassword()))){
                    txtRePwd.setBorder(BorderFactory.createLineBorder(Color.red));
                    jLabel3.setForeground(Color.red);
                }
                else {
                    txtRePwd.setBorder(border);
                    jLabel3.setForeground(Color.BLACK);
                }
            }

        });
        
        
    }
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username = txtUser.getText();
        String location = txtLocation.getText();
        String p1 = String.valueOf(txtPwd.getPassword());
        String p2 = String.valueOf(txtRePwd.getPassword());

        if (username == null || username.equals("")) {
            JOptionPane.showMessageDialog(null, "Empty office name");
            return;
        }
        
        if (location == null || location.equals("")) {
            JOptionPane.showMessageDialog(null, "Empty location");
        }
        
        if (p1 == null || p1.equals("")) {
            JOptionPane.showMessageDialog(null, "empty password");
            return;
        }
        if (!passwordPattern()) {
            JOptionPane.showMessageDialog(null, "Password should be at least 6 "
                + "digits and contain at least one upper case letter,"
                + " one lower case letter, one digit and one special "
                + "character $, *, # or &.");
            return;
        }
        
        if (!p1.equals(p2)) {
            JOptionPane.showMessageDialog(null, "Password mismatch");
        }

        
        
        TravelOffice to = new TravelOffice(username, p1);
        if (this.TA.getTravelOfficeDirectory().addTravelOffice(to)) 
            JOptionPane.showMessageDialog(null, "Register Travel Office successfully!");
        else {
            JOptionPane.showMessageDialog(null, "Already registered the same office name. Please change name!");
            return;
        }
//        ManageCustomerJPanel mc = new ManageCustomerJPanel(CardSequenceJPanel, TA, to);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        CardSequenceJPanel.remove(this);
        Component[] componentArray = this.CardSequenceJPanel.getComponents();
        for(Component comp : componentArray){
            if(comp instanceof TravelOfficeLogInJPanel){
                TravelOfficeLogInJPanel manageP = (TravelOfficeLogInJPanel) comp;
                manageP.initialize();
            }
        }
//        CardSequenceJPanel.add("ManageCustomer", mc);
        layout.previous(CardSequenceJPanel);   
    }//GEN-LAST:event_btnRegisterActionPerformed

    private boolean passwordPattern() {
        Pattern p = Pattern.compile("^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]))(?=.*[$*#&]).{6,}$");
        Matcher m = p.matcher(String.valueOf(txtPwd.getPassword()));
        boolean b = m.matches();
        return b;
    }
    
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtRePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JPasswordField txtRePwd;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
