/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Vehicle.Car;
import javax.swing.ImageIcon;
import javax.imageio.*;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JFrame;

/**
 *
 * @author mac
 */
public class DisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPanel
     */
    public DisplayPanel(Car car) {
        initComponents();
        displayCar(car);
    }

    private void displayCar(Car car) {
        
        String carMake = car.getMake();
        makeTextField.setText(carMake);
        
        String carModel = car.getModel();
        modelTextField.setText(carModel);
        
        String carPrice = car.getPrice();
        priceTextField.setText(carPrice);
        
        String carBodyStyle = car.getBodyStyle();
        bodyStyleTextField.setText(carBodyStyle);
        
        String carDoorNum = car.getDoorNum();
        doorNumTextField.setText(carDoorNum);
        
        String carExtColor = car.getExtColor();
        extColorTextField.setText(carExtColor);
        
        String carIntColor = car.getIntColor();
        intColorTextField.setText(carIntColor);
        
        String carCityMpg = car.getCityMpg();
        cityMpgTextField.setText(carCityMpg);
        
        String carHwyMpg = car.getHwyMpg();
        hwyMpgTextField.setText(carHwyMpg);
        
        String carFuelType = car.getFuelType();
        fuelTypeTextField.setText(carFuelType);
        
        String carEngine = car.getEngine();
        engineTextField.setText(carEngine);
        
        String carCylinders = car.getCylindersNum();
        cylindersTextField.setText(carCylinders);
        
        String carDimensions = car.getDimensions();
        dimensionsTextField.setText(carDimensions);
        
        String carDrivetrain = car.getDrivetrain();
        drivetrainTextField.setText(carDrivetrain);
        
        String carTransmission = car.getTransmission();
        transmissionTextField.setText(carTransmission);
        
        String carVin = car.getVin();
        vinTextField.setText(carVin);
        
        String carMileage = car.getMileage();
        mileageTextField.setText(carMileage);
        
        String carSpeakerNum = car.getSpeakerNum();
        speakerNumTextField.setText(carSpeakerNum);
        
        String carSeatNum = car.getSeatNum();
        seatNumTextField.setText(carSeatNum);
        
        String carSeatType = car.getSeatType();
        seatTypeTextField.setText(carSeatType);
        
        String imageName = car.getImageName();
        viewImageBtn.setName(imageName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        bodyStyleLabel = new javax.swing.JLabel();
        doorNumLabel = new javax.swing.JLabel();
        extColorNum = new javax.swing.JLabel();
        fuelTypeLabel = new javax.swing.JLabel();
        hwyMpgLabel = new javax.swing.JLabel();
        cityMpgLabel = new javax.swing.JLabel();
        intColorLabel = new javax.swing.JLabel();
        makeTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        bodyStyleTextField = new javax.swing.JTextField();
        doorNumTextField = new javax.swing.JTextField();
        extColorTextField = new javax.swing.JTextField();
        intColorTextField = new javax.swing.JTextField();
        cityMpgTextField = new javax.swing.JTextField();
        hwyMpgTextField = new javax.swing.JTextField();
        fuelTypeTextField = new javax.swing.JTextField();
        speakerNumTextField = new javax.swing.JTextField();
        seatNumTextField = new javax.swing.JTextField();
        seatTypeTextField = new javax.swing.JTextField();
        vinTextField = new javax.swing.JTextField();
        engineTextField = new javax.swing.JTextField();
        engineLabel = new javax.swing.JLabel();
        cylindersTextField = new javax.swing.JTextField();
        dimensionsTextField = new javax.swing.JTextField();
        cylindersLabel = new javax.swing.JLabel();
        dimensionsLabel = new javax.swing.JLabel();
        drivetrainLabel = new javax.swing.JLabel();
        transmissionLabel = new javax.swing.JLabel();
        mileageLabel = new javax.swing.JLabel();
        vinLabel = new javax.swing.JLabel();
        seatTypeLabel = new javax.swing.JLabel();
        drivetrainTextField = new javax.swing.JTextField();
        seatNumLabel = new javax.swing.JLabel();
        speakNumLabel = new javax.swing.JLabel();
        transmissionTextField = new javax.swing.JTextField();
        mileageTextField = new javax.swing.JTextField();
        viewImageBtn = new javax.swing.JButton();

        displayLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        displayLabel.setText("This's Your Favorite Car!");

        makeLabel.setText("Make:");

        modelLabel.setText("Model:");

        priceLabel.setText("Price:");

        bodyStyleLabel.setText("Body Style:");

        doorNumLabel.setText("Door Number:");

        extColorNum.setText("Exterior Color:");

        fuelTypeLabel.setText("Fuel Type:");

        hwyMpgLabel.setText("Highway MPG:");

        cityMpgLabel.setText("City MPG:");

        intColorLabel.setText("Interior Color:");

        makeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTextFieldActionPerformed(evt);
            }
        });

        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        bodyStyleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyStyleTextFieldActionPerformed(evt);
            }
        });

        doorNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorNumTextFieldActionPerformed(evt);
            }
        });

        extColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extColorTextFieldActionPerformed(evt);
            }
        });

        intColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intColorTextFieldActionPerformed(evt);
            }
        });

        cityMpgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityMpgTextFieldActionPerformed(evt);
            }
        });

        hwyMpgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hwyMpgTextFieldActionPerformed(evt);
            }
        });

        fuelTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypeTextFieldActionPerformed(evt);
            }
        });

        speakerNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakerNumTextFieldActionPerformed(evt);
            }
        });

        seatNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatNumTextFieldActionPerformed(evt);
            }
        });

        seatTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeTextFieldActionPerformed(evt);
            }
        });

        vinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinTextFieldActionPerformed(evt);
            }
        });

        engineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTextFieldActionPerformed(evt);
            }
        });

        engineLabel.setText("Engine:");

        cylindersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylindersTextFieldActionPerformed(evt);
            }
        });

        dimensionsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionsTextFieldActionPerformed(evt);
            }
        });

        cylindersLabel.setText("Cylinders:");

        dimensionsLabel.setText("Dimensions:");

        drivetrainLabel.setText("Drivetrain:");

        transmissionLabel.setText("Transmission:");

        mileageLabel.setText("Mileage:");

        vinLabel.setText("VIN:");

        seatTypeLabel.setText("Seat Type:");

        drivetrainTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivetrainTextFieldActionPerformed(evt);
            }
        });

        seatNumLabel.setText("Seat Number:");

        speakNumLabel.setText("Speaker Number:");

        transmissionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmissionTextFieldActionPerformed(evt);
            }
        });

        mileageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileageTextFieldActionPerformed(evt);
            }
        });

        viewImageBtn.setText("View image");
        viewImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewImageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(displayLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLabel)
                                    .addComponent(makeLabel))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelTextField)
                                    .addComponent(makeTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bodyStyleLabel)
                                    .addComponent(doorNumLabel)
                                    .addComponent(extColorNum)
                                    .addComponent(intColorLabel)
                                    .addComponent(cityMpgLabel)
                                    .addComponent(hwyMpgLabel)
                                    .addComponent(fuelTypeLabel)
                                    .addComponent(priceLabel))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTextField)
                                    .addComponent(fuelTypeTextField)
                                    .addComponent(cityMpgTextField)
                                    .addComponent(intColorTextField)
                                    .addComponent(doorNumTextField)
                                    .addComponent(bodyStyleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(extColorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hwyMpgTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cylindersLabel)
                                    .addComponent(engineLabel))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cylindersTextField)
                                    .addComponent(engineTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drivetrainLabel)
                                    .addComponent(transmissionLabel)
                                    .addComponent(mileageLabel)
                                    .addComponent(speakNumLabel)
                                    .addComponent(seatNumLabel)
                                    .addComponent(seatTypeLabel)
                                    .addComponent(vinLabel)
                                    .addComponent(dimensionsLabel))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimensionsTextField)
                                    .addComponent(vinTextField)
                                    .addComponent(seatNumTextField)
                                    .addComponent(speakerNumTextField)
                                    .addComponent(transmissionTextField)
                                    .addComponent(drivetrainTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(mileageTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(seatTypeTextField, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewImageBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(displayLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makeLabel)
                            .addComponent(makeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelLabel)
                            .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bodyStyleLabel)
                            .addComponent(bodyStyleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doorNumLabel)
                            .addComponent(doorNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extColorNum)
                            .addComponent(extColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intColorLabel)
                            .addComponent(intColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityMpgLabel)
                            .addComponent(cityMpgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hwyMpgLabel)
                            .addComponent(hwyMpgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelTypeLabel)
                            .addComponent(fuelTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineLabel)
                            .addComponent(engineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cylindersLabel)
                            .addComponent(cylindersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimensionsLabel)
                            .addComponent(dimensionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drivetrainLabel)
                            .addComponent(drivetrainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transmissionLabel)
                            .addComponent(transmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mileageLabel)
                            .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(speakNumLabel)
                            .addComponent(speakerNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatNumLabel)
                            .addComponent(seatNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatTypeLabel)
                            .addComponent(seatTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vinLabel)
                            .addComponent(vinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(viewImageBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void engineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTextFieldActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void bodyStyleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyStyleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyStyleTextFieldActionPerformed

    private void intColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intColorTextFieldActionPerformed

    private void hwyMpgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hwyMpgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hwyMpgTextFieldActionPerformed

    private void mileageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileageTextFieldActionPerformed

    private void makeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void doorNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doorNumTextFieldActionPerformed

    private void extColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extColorTextFieldActionPerformed

    private void cityMpgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityMpgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityMpgTextFieldActionPerformed

    private void fuelTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypeTextFieldActionPerformed

    private void cylindersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylindersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cylindersTextFieldActionPerformed

    private void dimensionsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionsTextFieldActionPerformed

    private void drivetrainTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivetrainTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drivetrainTextFieldActionPerformed

    private void transmissionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmissionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transmissionTextFieldActionPerformed

    private void speakerNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakerNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speakerNumTextFieldActionPerformed

    private void seatNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatNumTextFieldActionPerformed

    private void seatTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTypeTextFieldActionPerformed

    private void vinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinTextFieldActionPerformed

    private void viewImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewImageBtnActionPerformed
        // TODO add your handling code here:
        String imageName = viewImageBtn.getName();
        if(imageName == null) {
            JOptionPane.showMessageDialog(null, 
                    "Can't Find Picture of Your Car!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        ImageIcon IC = new ImageIcon("image/"+imageName);
//        int iconWidth = IC.getIconWidth();
//        int iconHeight = IC.getIconHeight();
        IC.setImage(IC.getImage());
//      IC.setImage(IC.getImage().getScaledInstance(300, 300*iconHeight/iconWidth, Image.SCALE_DEFAULT));
//        viewImageBtn.setIcon(IC);
        JLabel imageLabel = new JLabel(IC);
        JLabel label = new JLabel(IC);
        JFrame frame = new JFrame("Image");
        frame.add(label);
        frame.pack();
        frame.setVisible(true);        
    }//GEN-LAST:event_viewImageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodyStyleLabel;
    private javax.swing.JTextField bodyStyleTextField;
    private javax.swing.JLabel cityMpgLabel;
    private javax.swing.JTextField cityMpgTextField;
    private javax.swing.JLabel cylindersLabel;
    private javax.swing.JTextField cylindersTextField;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JTextField dimensionsTextField;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JLabel doorNumLabel;
    private javax.swing.JTextField doorNumTextField;
    private javax.swing.JLabel drivetrainLabel;
    private javax.swing.JTextField drivetrainTextField;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JTextField engineTextField;
    private javax.swing.JLabel extColorNum;
    private javax.swing.JTextField extColorTextField;
    private javax.swing.JLabel fuelTypeLabel;
    private javax.swing.JTextField fuelTypeTextField;
    private javax.swing.JLabel hwyMpgLabel;
    private javax.swing.JTextField hwyMpgTextField;
    private javax.swing.JLabel intColorLabel;
    private javax.swing.JTextField intColorTextField;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JLabel mileageLabel;
    private javax.swing.JTextField mileageTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel seatNumLabel;
    private javax.swing.JTextField seatNumTextField;
    private javax.swing.JLabel seatTypeLabel;
    private javax.swing.JTextField seatTypeTextField;
    private javax.swing.JLabel speakNumLabel;
    private javax.swing.JTextField speakerNumTextField;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JTextField transmissionTextField;
    private javax.swing.JButton viewImageBtn;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField vinTextField;
    // End of variables declaration//GEN-END:variables
}
